sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --trace #--quiet

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
  - GITHUB_REPO: eleazarbr/eleazarbr.github.io
  - secure: jcrlQM7Q+eznhtyEl+fh2FEINk41nVc03At5tmvLJVhzuo2ZhV31wzaRPAZAZno/smpDUsGvuaiv3Dy/dEIASb/TJ+bDESDThvoODYdKf4kPN3a4oSUfYqRsZiLifFuRAwRbYe3oc5++szV/nHmy4CqkWE8FXPqJ5XifiOh6J2CdoNOAAGpTSK55ruwFunrwljSLRXFtOUauGsfNO3E71B/dwWnV63m1B1W/IE9/k1stFEnquhg0BLAlAIc8QGhAlyqMyjVCnW4mi1KWIwkbbcj0JzOjEwdtNZj9OW7Dj1JiqkzoV0NCEqHJSR5aEiv156bNIZcIo3hm1scCp9Moqh+SsdvbLlgeEae9PyMbVci6nWUlWZVHZ+L8S2qTBk/PnyW8l23eDCdtQWE+zp44cuM1uQH7pgqvs4IiJVryrAM8d0+1EKib62XRqNHgUmTnzqngpy9MOdb/J8ATKpoqo+yASJjqIusggzstARdmDyO00lROtvmH/XS7lXhCO+V9/ZWohdikBCt5q4VELHmU4V6c1sfCAxw+p4YLWMFBIu5UoPPtbsqe0cW/h9uk8nqm5hZdw/AEM/hCWatL6/aWLgQJ7jMj4hY+durAQny+NDFl46PbssY5GGGsvpUsPi987DSHaVF6uAAsB+RggY4liMTxd+7r3hkdVXHdbzcmjZE=
branches:
  only:
  - master
