sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --trace #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "L00ilz7mp2Bq3p2jdWLTvlI4Tlv1+yHUDpxtc+YyNk1MlXrjjTCOrU47sqB2ZjfmmmvmNXQY4omS9KV5mBoqzkyPW+YWiAzcfR35e6mekr5F0YnXTslEnyQl432j8D9gW002oGlZmOjKNWvQ2Uh7UCt8Ys44m+HV9YmPvDU3m/bXyyvbc2vrz0QmjrsenmCkd8GI143S4J3GcltRKyAPCPBVENR3THHQ6j/6PQViH+dKESS7dvkwggv4y7U/9L9GM+GYOcOck4J94SSAdxBftxSXKoQHX3jkQqdAuGIPAp0UrESql0ncJwfxd4R5iSbO13XXQRvyanGlHnkWH/WS4NzPVZgbGlGWxgurbpOQmf970WmVh7Vw+2TonvmSeGfgKcQFJjeuFKa2BrqrvOq8xPGkOoY+PELFI1Vi2UTKZs5d3spieTjrFvAJYZVdvXKakORPW+2m15poqIi01HlK1WazxrqEpld5cvE2p6EBU6k2ak8sHotdVZef34o2tOU1DwSnl8SN/Q3E75Sl8rwFL5g9HupprQH7P226RJ8u6lZ06jE0vXuP2LNuG4YRixg8BzQDaujPqnwt8UdDMzKDBKOEK0vLxxCtPSg9pahq++vTqpEEeIvhtXwIzKmQZ9qUZsmgH4romMnZ7440YWSivt9J/1eaU0Di/6iBQcZmEbk="
branches:
  only:
    - master
