# Site settings
title: 'Eleazar Resendez'
description: "I'm a very passionate Web Developer and Software Engineer, constantly experimenting with new technologies and striving to better as a developer and the development community as a whole."
baseurl: ''
url: 'https://eresendez.com'
google_analytics: 'UA-45112924-2'
disqus_shortname: 'eleazar-resendez'

author:
  name: 'Eleazar Resendez'
  email: e.resendez@outlook.com
  twitter_username: eleazarbr
  # facebook_username: eleazarbrr
  github_username: eleazarbr
  linkedin_username: eleazarbr
  coderwall_username: eresendez

logo: https://avatars1.githubusercontent.com/u/4369018

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
