title: Eleazar Resendez
email: eleazar.resendez@outlook.com
description: Eleazar Resendez Personal Website
baseurl: "" # the subpath of the site, e.g. /blog
url: "https://eresendez.com" # the base hostname & protocol for the site e.g. http://example.com

author:
  name: Eleazar Resendez
  picture: https://avatars1.githubusercontent.com/u/4369018
  twitter: eleazarbr

twitter_username: eleazarbr
github_username: eleazarbr

logo: https://avatars1.githubusercontent.com/u/4369018

social:
  links:
    - https://github.com/eleazarbr
    - https://twitter.com/eleazarbr

google_site_verification: ""

markdown: kramdown
exclude: [Gemfile, Gemfile.lock, LICENSE, README.md]
sass:
  style: compressed
  sass_dir: assets/styles

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji